configs/nsh_minidisplay: add LV_USE_NUTTX_LIBUV for QuickApp Kconfig dep
QUICKAPP depends on LV_USE_NUTTX_LIBUV in Kconfig. The nsh_minidisplay
defconfig had LV_USE_NUTTX_LCD but was missing LV_USE_NUTTX_LIBUV,
which caused CONFIG_QUICKAPP=y to be silently dropped by Kconfig
dependency resolution. This in turn left CONFIG_HAP_APP_PATH undefined,
resulting in a compile error in audio_impl.c:

  feature/audio_impl.c:816: error: 'CONFIG_HAP_APP_PATH' undeclared

Add CONFIG_LV_USE_NUTTX_LIBUV=y so that QUICKAPP's Kconfig dependency
is satisfied and CONFIG_HAP_APP_PATH="/data" is auto-set.

Signed-off-by: v-yanxingyu <v-yanxingyu@xiaomi.com>